# fly.toml app configuration file generated for ghd-client on 2023-05-06T20:13:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ghd-client"
primary_region = "otp"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
